package Bean;

// Generated Apr 5, 2013 10:11:59 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Blob;
import java.util.Date;

import org.genericdao.PrimaryKey;



/**
 * Game generated by hbm2java
 */
@PrimaryKey("gameID")
public class Game implements Comparable<Game>{
	private int gameID;
	private int fstID;
	private int sndID;
	private byte[] process;   
	private int fstScore;
	private int sndScore;
	private Date GameDate;

	public Game() {
	}

	public Game(int fstID, int sndID, int fstScore, int sndScore, Date GameDate) {
		this.fstID = fstID;
		this.sndID = sndID;
		this.fstScore = fstScore;
		this.sndScore = sndScore;
		this.GameDate = GameDate;
	}

	public Game(int fstID, int sndID, byte[] process, int fstScore,
			int sndScore, Date GameDate) {
		this.fstID = fstID;
		this.sndID = sndID;
		this.process = process;
		this.fstScore = fstScore;
		this.sndScore = sndScore;
		this.GameDate = GameDate;
	}

	public int getGameID() {
		return this.gameID;
	}

	public void setGameID(int gameID) {
		this.gameID = gameID;
	}

	public int getFstID() {
		return this.fstID;
	}

	public void setFstID(int fstID) {
		this.fstID = fstID;
	}

	public int getSndID() {
		return this.sndID;
	}

	public void setSndID(int sndID) {
		this.sndID = sndID;
	}

	public byte[] getProcess() {
		return this.process;
	}

	public void setProcess(byte[] process) {
		this.process = process;
	}

	public int getFstScore() {
		return this.fstScore;
	}

	public void setFstScore(int fstScore) {
		this.fstScore = fstScore;
	}

	public int getSndScore() {
		return this.sndScore;
	}

	public void setSndScore(int sndScore) {
		this.sndScore = sndScore;
	}

	public Date getGameDate() {
		return this.GameDate;
	}

	public void setGameDate(Date GameDate) {
		this.GameDate = GameDate;
	}

	@Override
	public int compareTo(Game other) {
		int c = GameDate.compareTo(other.GameDate);
		if (c != 0)
			return c;
		return 0;
	}

}
